/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/icons/IconAppointment copy 2.vue')['default']
    3: typeof import('./src/components/icons/IconAppointment copy 3.vue')['default']
    copy: typeof import('./src/components/icons/IconSettings copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAppointment: typeof import('./src/components/icons/IconAppointment.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDashboard: typeof import('./src/components/icons/IconDashboard.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconHelp: typeof import('./src/components/icons/IconHelp.vue')['default']
    IconLabTest: typeof import('./src/components/icons/IconLabTest.vue')['default']
    IconMedicineOrder: typeof import('./src/components/icons/IconMedicineOrder.vue')['default']
    IconMessage: typeof import('./src/components/icons/IconMessage.vue')['default']
    IconPayment: typeof import('./src/components/icons/IconPayment.vue')['default']
    IconSettings: typeof import('./src/components/icons/IconSettings.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ProfileInfo: typeof import('./src/components/Header/ProfileInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDown: typeof import('./src/components/Dropdown/SearchDown.vue')['default']
    SearchInput: typeof import('./src/components/Input/SearchInput.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TextInput: typeof import('./src/components/Input/TextInput.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TopHeader: typeof import('./src/components/TopHeader.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
